# Generated by Django 5.1.5 on 2025-01-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Новости', max_length=200, verbose_name='Название статьи')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: сегодня 2025 года будет праздник!', max_length=200, verbose_name='Название статьи')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Изображение поста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
